update

diff --git a/packages/scripts/bin/blog b/packages/scripts/bin/blog
--- a/packages/scripts/bin/blog
+++ b/packages/scripts/bin/blog
@@ -30,17 +30,52 @@ if [ -z "$1" ]; then
 	set +o noglob
 else
 	# check if arg is a file inside NOTE_PATH
-	if [ -f "$NOTE_PATH/$1.txt" ]; then
-		editor "$NOTE_PATH/$1.txt"
-	else
-		# create file
-		# ask for confirmation
-		read -p "Create new note '$1'? [y/N] " -n 1 -r
-		echo
-		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-			exit 1
+	FOUND_FILE=""
+	for ext in "${EXTS[@]}"; do
+		if [ -f "$NOTE_PATH/$1.$ext" ]; then
+			FOUND_FILE="$NOTE_PATH/$1.$ext"
+			break
 		fi
-		touch "$NOTE_PATH/$1.txt"
-		editor "$NOTE_PATH/$1.txt"
+	done
+	if [ ! -z "$FOUND_FILE" ]; then
+		editor "$FOUND_FILE"
+		exit 0
 	fi
+
+	# create file if it doesn't exist
+	if [ ! -d "$NOTE_PATH" ]; then
+		mkdir -p "$NOTE_PATH"
+	fi
+
+	read -p "Create new note '$1'? [y/N] " -n 1 -r
+	echo
+	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+		exit 1
+	fi
+	# ask for extension from user with choice of EXTS
+	echo "Please choose extension:"
+	select ext in "${EXTS[@]}"; do
+		if [ -z "$ext" ]; then
+			echo "Invalid choice"
+		else
+			break
+		fi
+	done
+
+	touch "$NOTE_PATH/$1.$ext"
+	editor "$NOTE_PATH/$1.$ext"
+
+	# if [ -f "$NOTE_PATH/$1.txt" ]; then
+	# 	editor "$NOTE_PATH/$1.txt"
+	# else
+	# 	# create file
+	# 	# ask for confirmation
+	# 	read -p "Create new note '$1'? [y/N] " -n 1 -r
+	# 	echo
+	# 	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+	# 		exit 1
+	# 	fi
+	# 	touch "$NOTE_PATH/$1.txt"
+	# 	editor "$NOTE_PATH/$1.txt"
+	# fi
 fi
diff --git a/packages/scripts/bin/bo b/packages/scripts/bin/bo
--- a/packages/scripts/bin/bo
+++ b/packages/scripts/bin/bo
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 
-if [ "x$BOOKMARKS_FILE" == "x" ]; then
-  echo -e "\033[1;31mERROR\033[0m: BOOKMARKS_FILE env variable doesn't exist"
-  exit 1
+if [ "x$RS_BOOKMARKS_FILE" == "x" ]; then
+	echo -e "\033[1;31mERROR\033[0m: RS_BOOKMARKS_FILE env variable doesn't exist"
+	exit 1
 fi
 
-if [[ ! -f "$BOOKMARKS_FILE" ]]; then
-  echo -e "\033[1;31mERROR\033[0m: BOOKMARKS_FILE env variable doesn't exist"
-  exit 1
+if [[ ! -f "$RS_BOOKMARKS_FILE" ]]; then
+	echo -e "\033[1;31mERROR\033[0m: RS_BOOKMARKS_FILE env variable doesn't point to a file"
+	exit 1
 fi
 
-editor "$BOOKMARKS_FILE"
+editor "$RS_BOOKMARKS_FILE"
diff --git a/packages/scripts/bin/tmux-sessionizer b/packages/scripts/bin/tmux-sessionizer
--- a/packages/scripts/bin/tmux-sessionizer
+++ b/packages/scripts/bin/tmux-sessionizer
@@ -3,63 +3,69 @@
 ### tmux sessionizer
 ### https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer
 tmux-sessionizer() {
-  tmux_running=$(pgrep tmux)
+	tmux_running=$(pgrep tmux)
 
-  if [[ $# -eq 1 ]]; then
-    selected=$1
-  else
-    # find .git in the specified directory and then go up one level
-    ARR=($(find "$HOME/Projects" "$HOME/Ucare" "$HOME/TA" -mindepth 1 -maxdepth 1 -type d -exec test -e "{}/.git" ';' -print -prune))
-    ARR+=($(find "$HOME/Personal" -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' -not -path '*/\.*/*'))
-    ARR+=("$HOME/.config/nix-config")
-    ARR+=("$HOME/.config/nvim")
-    ARR+=("$HOME/Code")
-    ARR+=("$HOME/Code/website")
-    ARR+=("$HOME/Projects")
-    ARR+=("$HOME/Personal")
-    ARR+=("$HOME/Screenshots")
-    # split OLD-<name> to different array
-    OLD_ARR=()
-    for i in "${ARR[@]}"; do
-      if [[ $i == *"OLD-"* ]]; then
-        OLD_ARR+=("$i")
-      fi
-    done
-    ARR=("${ARR[@]/${OLD_ARR[@]}}") # remove OLD-<name> from ARR
-    ARR=($(printf '%s\n' "${ARR[@]}" | sort -u)) # sort arr and remove duplicates
-    ARR+=("${OLD_ARR[@]}") # add OLD-<name> to the end of ARR
+	if [[ $# -eq 1 ]]; then
+		selected=$1
+	else
+		# find .git in the specified directory and then go up one level
+		ARR=($(find "$HOME/Projects" "$HOME/Ucare" "$HOME/TA" "$HOME/Ucare/papers/" -mindepth 1 -maxdepth 1 -type d -exec test -e "{}/.git" ';' -print -prune))
+		ARR+=($(find "$HOME/Personal" -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' -not -path '*/\.*/*'))
+		ARR+=("$HOME/.config/nix-config")
+		ARR+=("$HOME/.config/nvim")
+		ARR+=("$HOME/Code")
+		ARR+=("$HOME/Code/website")
+		ARR+=("$HOME/Projects")
+		ARR+=("$HOME/Personal")
+		ARR+=("$HOME/Screenshots")
 
-    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
-      if [[ "$OSTYPE" == "darwin"* ]]; then
-        selected=$(printf '%s\n' "${ARR[@]}" | fzf --reverse --preview 'tree -C {} | head -200' --preview-window=right:50% --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --no-sort)
-      else
-        selected=$(printf '%s\n' "${ARR[@]}" | fzf --reverse --preview 'tree -C {} | head -200' --preview-window=right:50% --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --no-sort)
-      fi
-    else
-      if [[ "$OSTYPE" == "darwin"* ]]; then
-        selected=$(printf '%s\n' "${ARR[@]}" | fzf-tmux -p 90% --reverse --preview 'tree -C {} | head -200' --preview-window=right:50% --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --no-sort)
-      else
-        selected=$(printf '%s\n' "${ARR[@]}" | fzf-tmux -p 90% --reverse --preview 'tree -C {} | head -200' --preview-window=right:50% --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --no-sort)
-      fi
-    fi
-  fi
+		TA_DIRS=($(find "$HOME/TA" -mindepth 2 -maxdepth 2 -type d -not -path '*/\.*' -not -path '*/\.*/*'))
+		for dir in "${TA_DIRS[@]}"; do
+			ARR+=("$dir")
+		done
 
-  if [[ -z $selected ]]; then
-    exit 0
-  fi
+		# split OLD-<name> to different array
+		OLD_ARR=()
+		for i in "${ARR[@]}"; do
+			if [[ $i == *"OLD-"* ]]; then
+				OLD_ARR+=("$i")
+			fi
+		done
+		ARR=("${ARR[@]/${OLD_ARR[@]}/}")             # remove OLD-<name> from ARR
+		ARR=($(printf '%s\n' "${ARR[@]}" | sort -u)) # sort arr and remove duplicates
+		ARR+=("${OLD_ARR[@]}")                       # add OLD-<name> to the end of ARR
 
-  selected_name=$(basename "$selected" | tr . _)
+		if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
+			if [[ "$OSTYPE" == "darwin"* ]]; then
+				selected=$(printf '%s\n' "${ARR[@]}" | fzf --reverse --preview 'tree -C {} | head -200' --preview-window=right:50% --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --no-sort)
+			else
+				selected=$(printf '%s\n' "${ARR[@]}" | fzf --reverse --preview 'tree -C {} | head -200' --preview-window=right:50% --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --no-sort)
+			fi
+		else
+			if [[ "$OSTYPE" == "darwin"* ]]; then
+				selected=$(printf '%s\n' "${ARR[@]}" | fzf-tmux -p 90% --reverse --preview 'tree -C {} | head -200' --preview-window=right:50% --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --no-sort)
+			else
+				selected=$(printf '%s\n' "${ARR[@]}" | fzf-tmux -p 90% --reverse --preview 'tree -C {} | head -200' --preview-window=right:50% --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --no-sort)
+			fi
+		fi
+	fi
 
-  if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
-    tmux new-session -s $selected_name -c $selected
-    exit 0
-  fi
+	if [[ -z $selected ]]; then
+		exit 0
+	fi
 
-  if ! tmux has-session -t=$selected_name 2> /dev/null; then
-    tmux new-session -ds $selected_name -c $selected
-  fi
+	selected_name=$(basename "$selected" | tr . _)
 
-  tmux switch-client -t $selected_name
+	if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
+		tmux new-session -s $selected_name -c $selected
+		exit 0
+	fi
+
+	if ! tmux has-session -t=$selected_name 2>/dev/null; then
+		tmux new-session -ds $selected_name -c $selected
+	fi
+
+	tmux switch-client -t $selected_name
 }
 
 tmux-sessionizer "$@"
