remove glob in some case

diff --git a/packages/scripts/bin/blog b/packages/scripts/bin/blog
--- a/packages/scripts/bin/blog
+++ b/packages/scripts/bin/blog
@@ -2,17 +2,17 @@
 
 # check if RS_PROJECT_NOTES env variable exists
 if [ -z "$RS_BLOG_NOTES" ]; then
-  echo -e "\033[1;31mERROR\033[0m: RS_BLOG_NOTES env variable doesn't exist"
-  exit 1
+	echo -e "\033[1;31mERROR\033[0m: RS_BLOG_NOTES env variable doesn't exist"
+	exit 1
 fi
 
 if [ ! -d "$RS_BLOG_NOTES" ]; then
-  echo -e "\033[1;31mERROR\033[0m: RS_BLOG_NOTES env variable doesn't point to a directory"
-  exit 1
+	echo -e "\033[1;31mERROR\033[0m: RS_BLOG_NOTES env variable doesn't point to a directory"
+	exit 1
 fi
 
 if [ -z "$RS_NOTES_EXTS" ]; then
-  RS_NOTES_EXTS="md txt"
+	RS_NOTES_EXTS="md txt"
 fi
 
 NOTE_PATH="$RS_BLOG_NOTES"
@@ -20,26 +20,27 @@ EXTS=($RS_NOTES_EXTS)
 
 # check if first arg exists
 if [ -z "$1" ]; then
-
-  if [[ "$OSTYPE" == "darwin"* ]]; then
-    find "$NOTE_PATH" -type f -name "*.${EXTS[0]}" -o -name "*.${EXTS[1]}" | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
-  else
-    # linux
-    find "$NOTE_PATH" -type f -name "*.${EXTS[0]}" -o -name "*.${EXTS[1]}" | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
-  fi
+	set -o noglob
+	if [[ "$OSTYPE" == "darwin"* ]]; then
+		find "$NOTE_PATH" -type f -name "*.${EXTS[0]}" -o -name "*.${EXTS[1]}" | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
+	else
+		# linux
+		find "$NOTE_PATH" -type f -name "*.${EXTS[0]}" -o -name "*.${EXTS[1]}" | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
+	fi
+	set +o noglob
 else
-  # check if arg is a file inside NOTE_PATH
-  if [ -f "$NOTE_PATH/$1.txt" ]; then
-    editor "$NOTE_PATH/$1.txt"
-  else
-    # create file
-    # ask for confirmation
-    read -p "Create new note '$1'? [y/N] " -n 1 -r
-    echo
-    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-      exit 1
-    fi
-    touch "$NOTE_PATH/$1.txt"
-    editor "$NOTE_PATH/$1.txt"
-  fi
+	# check if arg is a file inside NOTE_PATH
+	if [ -f "$NOTE_PATH/$1.txt" ]; then
+		editor "$NOTE_PATH/$1.txt"
+	else
+		# create file
+		# ask for confirmation
+		read -p "Create new note '$1'? [y/N] " -n 1 -r
+		echo
+		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+			exit 1
+		fi
+		touch "$NOTE_PATH/$1.txt"
+		editor "$NOTE_PATH/$1.txt"
+	fi
 fi
diff --git a/packages/scripts/bin/n b/packages/scripts/bin/n
--- a/packages/scripts/bin/n
+++ b/packages/scripts/bin/n
@@ -2,12 +2,12 @@
 
 # check if NOTES_DIRS env variable exists
 if [ -z "$RS_NOTES_DIRS" ]; then
-  echo -e "\033[1;31mERROR\033[0m: RS_NOTES_DIRS env variable doesn't exist"
-  exit 1
+	echo -e "\033[1;31mERROR\033[0m: RS_NOTES_DIRS env variable doesn't exist"
+	exit 1
 fi
 
 if [ -z "$RS_NOTES_EXTS" ]; then
-  RS_NOTES_EXTS="md txt"
+	RS_NOTES_EXTS="md txt"
 fi
 
 # RS_NOTES_DIRS is string with directories separated by space
@@ -19,31 +19,37 @@ NOTES_DIRS=($RS_NOTES_DIRS)
 EXTS=($RS_NOTES_EXTS)
 EXT_QUERIES=""
 for EXT in "${EXTS[@]}"; do
-  if [ "x$EXT_QUERIES" == "x" ]; then
-    EXT_QUERIES="-iname *.${EXT}"
-  else
-    EXT_QUERIES+=" -o -iname *.${EXT}"
-  fi
+	if [ "x$EXT_QUERIES" == "x" ]; then
+		EXT_QUERIES="-iname *.${EXT}"
+	else
+		EXT_QUERIES+=" -o -iname *.${EXT}"
+	fi
 done
+
 FILES=()
 
 # iterate over NOTES_DIRS
 for DIR in "${NOTES_DIRS[@]}"; do
-  # check if directory exists
-  if [ ! -d "$DIR" ]; then
-    # warning, yellow
-    echo -e "\033[1;33mWARNING\033[0m: $DIR doesn't exist, skipping..."
-    continue
-  fi
+	# check if directory exists
+	if [ ! -d "$DIR" ]; then
+		# warning, yellow
+		echo -e "\033[1;33mWARNING\033[0m: $DIR doesn't exist, skipping..."
+		continue
+	fi
 
-  # get files with arbitrary number of extensions
-  FILES+=($(find "$DIR" ${EXT_QUERIES} -type f))
-  # echo "Found ${#FILES[@]} files"
+	# get files with arbitrary number of extensions
+
+	set -o noglob
+	FILES+=($(find -L "$DIR" ${EXT_QUERIES} -type f))
+	set +o noglob
+	# echo "Found ${#FILES[@]} files"
 done
 
+echo "Found ${#FILES[@]} files"
+
 if [[ "$OSTYPE" == "darwin"* ]]; then
-  printf '%s\n' "${FILES[@]}" | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
+	printf '%s\n' "${FILES[@]}" | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
 else
-  # linux
-  printf '%s\n' "${FILES[@]}" | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
+	# linux
+	printf '%s\n' "${FILES[@]}" | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
 fi
diff --git a/packages/scripts/bin/p b/packages/scripts/bin/p
--- a/packages/scripts/bin/p
+++ b/packages/scripts/bin/p
@@ -2,80 +2,80 @@
 
 # check if RS_PROJECT_NOTES env variable exists
 if [ -z "$RS_PROJECT_NOTES" ]; then
-  echo -e "\033[1;31mERROR\033[0m: RS_PROJECT_NOTES env variable doesn't exist"
-  exit 1
+	echo -e "\033[1;31mERROR\033[0m: RS_PROJECT_NOTES env variable doesn't exist"
+	exit 1
 fi
 
-
 if [ ! -d "$RS_PROJECT_NOTES" ]; then
-  echo -e "\033[1;31mERROR\033[0m: RS_PROJECT_NOTES env variable doesn't point to a directory"
-  exit 1
+	echo -e "\033[1;31mERROR\033[0m: RS_PROJECT_NOTES env variable doesn't point to a directory"
+	exit 1
 fi
 
 if [ -z "$RS_NOTES_EXTS" ]; then
-  RS_NOTES_EXTS="md txt"
+	RS_NOTES_EXTS="md txt"
 fi
 
 VERBOSE=0
 FORCE=0
 FILE=""
 if [ $# -gt 0 ]; then
- while [ $# -gt 0 ]; do
-   case "$1" in
-      -f|--force)
-        FORCE=1
-        shift
-        exit
-        ;;
-      -v)
-        VERBOSE=1
-        shift
-        ;;
-      *)
-        if [ -z "$FILE" ]; then
-          FILE="$1"
-        fi
-        shift
-        ;;
-    esac
-  done
+	while [ $# -gt 0 ]; do
+		case "$1" in
+		-f | --force)
+			FORCE=1
+			shift
+			exit
+			;;
+		-v)
+			VERBOSE=1
+			shift
+			;;
+		*)
+			if [ -z "$FILE" ]; then
+				FILE="$1"
+			fi
+			shift
+			;;
+		esac
+	done
 fi
-
 
 NOTE_PATH="$RS_PROJECT_NOTES"
 EXTS=($RS_NOTES_EXTS)
 
 EXT_QUERIES=""
 for EXT in "${EXTS[@]}"; do
-  if [ "x$EXT_QUERIES" == "x" ]; then
-    EXT_QUERIES="-iname *.${EXT}"
-  else
-    EXT_QUERIES+=" -o -iname *.${EXT}"
-  fi
+	if [ "x$EXT_QUERIES" == "x" ]; then
+		EXT_QUERIES="-iname *.${EXT}"
+	else
+		EXT_QUERIES+=" -o -iname *.${EXT}"
+	fi
 done
 
 if [ "x$FILE" == "x" ]; then
-  if [[ "$OSTYPE" == "darwin"* ]]; then
-    find "$NOTE_PATH" -type f $EXT_QUERIES | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
-  else
-    # linux
-    find "$NOTE_PATH" -type f $EXT_QUERIES | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
-  fi
+	set -o noglob
+	if [[ "$OSTYPE" == "darwin"* ]]; then
+		find "$NOTE_PATH" -type f $EXT_QUERIES | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | pbcopy)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
+	else
+		# linux
+		find "$NOTE_PATH" -type f $EXT_QUERIES | fzf --bind "ctrl-y:execute-silent(echo {} | tr -d '\n' | xclip -selection clipboard)+abort" --ansi --height 100% --reverse --border --inline-info --preview-window=right:70% --preview 'bat --color=always --style=numbers --line-range :500 {}' --bind "enter:execute(editor {})+abort"
+	fi
+	set +o noglob
 else
-  # check if arg is a file inside NOTE_PATH
-  if [ -f "$NOTE_PATH/$FILE.txt" ]; then
-    editor "$NOTE_PATH/$FILE.txt"
-  else
-    if [ $FORCE -eq 1 ]; then
-      if [ $VERBOSE -eq 1 ]; then
-        echo -e "\033[1;33mWARNING\033[0m: $1 doesn't exist, creating..."
-      fi
-      touch "$NOTE_PATH/$FILE.txt"
-      editor "$NOTE_PATH/$FILE.txt"
-      exit 0
-    fi
+	# check if arg is a file inside NOTE_PATH
+	if [ -f "$NOTE_PATH/$FILE.txt" ]; then
+		editor "$NOTE_PATH/$FILE.txt"
+	else
+		if [ $FORCE -eq 1 ]; then
+			if [ $VERBOSE -eq 1 ]; then
+				echo -e "\033[1;33mWARNING\033[0m: $1 doesn't exist, creating..."
+			fi
+			touch "$NOTE_PATH/$FILE.txt"
+			editor "$NOTE_PATH/$FILE.txt"
+			exit 0
+		fi
 
-    echo -e "\033[1;31mERROR\033[0m: '$NOTE_PATH/$FILE.txt' doesn't exist"
-    echo -e "\033[1;34mINFO\033[0m: Use \033[1;32m-f/--force\033[0m to create it"
-  fi
+		echo -e "\033[1;31mERROR\033[0m: '$NOTE_PATH/$FILE.txt' doesn't exist"
+		echo -e "\033[1;34mINFO\033[0m: Use \033[1;32m-f/--force\033[0m to create it"
+	fi
 fi
